# Generated by Django 4.1.2 on 2022-10-21 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_username'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='FcUser',
        ),
        migrations.AlterModelTable(
            name='fcuser',
            table='FcUser',
        ),
    ]
