# Generated by Django 4.1.2 on 2022-10-21 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_rename_user_fcuser_alter_fcuser_table"),
    ]

    operations = [
        migrations.AlterModelTable(name="fcuser", table="fcuser",),
    ]
