# Generated by Django 4.1.2 on 2022-10-21 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_alter_fcuser_table"),
    ]

    operations = [
        migrations.RenameModel(old_name="FcUser", new_name="FcUser2",),
        migrations.AlterModelTable(name="fcuser2", table="fcuser1",),
    ]
