# Generated by Django 4.1.2 on 2022-10-21 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_rename_fcuser_fcuser2_alter_fcuser2_table"),
    ]

    operations = [
        migrations.RenameModel(old_name="FcUser2", new_name="Fcuser",),
        migrations.AlterModelTable(name="fcuser", table="fcuser",),
    ]
