# Generated by Django 4.1.2 on 2022-10-22 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0006_rename_fcuser2_fcuser_alter_fcuser_table"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="fcuser",
            options={"verbose_name": "패스트캠퍼스 사용자", "verbose_name_plural": "패스트캠퍼스 사용자"},
        ),
        migrations.AddField(
            model_name="fcuser",
            name="useremail",
            field=models.EmailField(
                default="test@gmail.com", max_length=128, verbose_name="이메일"
            ),
            preserve_default=False,
        ),
    ]
